# Generated by Django 2.1.5 on 2019-11-17 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_parttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothes.PartType'),
        ),
    ]
