# Generated by Django 2.1.5 on 2019-11-17 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_auto_20191117_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothings', to=settings.AUTH_USER_MODEL),
        ),
    ]
